// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import ApplyAlertController from "./apply_alert_controller"
application.register("apply-alert", ApplyAlertController)

import ChatroomDisplayController from "./chatroom_display_controller"
application.register("chatroom-display", ChatroomDisplayController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import SearchMissionsController from "./search_missions_controller"
application.register("search-missions", SearchMissionsController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)
