meta_name: "Helpderly"
meta_title: "Helpderly - Find support for your elderly"
meta_description: "Find support for your elderly - Help an elderly during your free time"
meta_image: "default_meta_image.jpg" # should exist in `app/assets/images/`
